### ISSUE TITLE
Errors on latest torchsparse release

### ISSUE THREAD

**Issue by CCInc** [mit-han-lab/spvnas#61]
The imports of spvnas need to be updated based on the renaming on the latest torchsparse commits, particularly:
```

Traceback (most recent call last):
  File "train.py", line 103, in <module>
    main()
  File "train.py", line 68, in main
    model = builder.make_model().cuda()
  File "/media/chris/Elements/data/PC/spvnas/core/builder.py", line 39, in make_model
    from core.models.semantic_kitti import SPVCNN
  File "/media/chris/Elements/data/PC/spvnas/core/models/semantic_kitti/__init__.py", line 2, in <module>
    from .spvcnn import *
  File "/media/chris/Elements/data/PC/spvnas/core/models/semantic_kitti/spvcnn.py", line 12, in <module>
    from torchsparse.utils.kernel_region import *
ModuleNotFoundError: No module named 'torchsparse.utils.kernel_region'

```

**Comment by zhijian-liu** [comment]
Just fixed. Thanks!

**Comment by CCInc** [comment]
@zhijian-liu I think there's a few more imports of `torchsparse.utils.kernel_region` in the code as well, in `core/models`
