### ISSUE TITLE
MPI install issues 

### ISSUE THREAD

**Issue by guragamb** [mit-han-lab/spvnas#65]
Hi, I get the following error when trying to train SPVCNN (mpi4py was already installed). 
```
(spvnas) ~root# torchpack dist-run -np 4 python train.py configs/semantic_kitti/spvcnn/cr0p5.yaml
OpenCV is built with OpenMP support. This usually results in poor performance. For details, see https://github.com/tensorpack/benchmarks/blob/master/ImageNet/benchmark-opencv-resize.py
Failed to import tensorflow.
Traceback (most recent call last):
  File "train.py", line 106, in <module>
    main()
  File "train.py", line 23, in main
    dist.init()
  File "/opt/conda/envs/spvnas/lib/python3.8/site-packages/torchpack/distributed/context.py", line 15, in init
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[16228,1],3]
  Exit code:    1
--------------------------------------------------------------------------
```
Do you have any idea what could be causing this MPI issue? Thanks!

**Comment by zhijian-liu** [comment]
This error does not seem to be related to `spvnas` and `torchpack`. Could you please double-check whether `mpi4py` is correctly installed (by `import mpi4py`)?
